services:
  db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=miniflux
    volumes:
      - /mnt/nas/docker/miniflux/db:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      start_period: 30s
    networks:
      # labnet:
      #   ipv4_address: 172.20.0.14
      - labnet
  miniflux:
    image: miniflux/miniflux:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      # labnet:
      #   ipv4_address: 172.20.0.13
      - labnet

networks:
  labnet:
    external: true
