services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - /mnt/nas/docker/wg-easy/wireguard:/etc/wireguard
    network_mode: "host"
    # ports:
    #   - "5000:5000/udp"
    #   - "51821:51821/tcp"
    restart: always # unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1
    environment:
      # Required:
      LANG: en
      WG_HOST: ddns.hisbaan.com

      # Optional:
      PASSWORD_HASH: ${PASSWORD_HASH}
      PORT: 51821
      WG_PORT: 5000
      WG_DEFAULT_ADDRESS: 192.168.10.x
      WG_DEVICE: enp4s0
      WG_DEFAULT_DNS: 1.1.1.1,1.0.0.1
      # WG_MTU: 1420
      WG_ALLOWED_IPS: 0.0.0.0/0,::/0
      WG_PERSISTENT_KEEPALIVE: 25
      UI_TRAFFIC_STATS: true
      UI_CHART_TYPE: 1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
