services:
  supabase-inactive-fix:
    build:
      context: build-context
    restart: "always"
    environment:
      TYPIST_SUPABASE_KEY: ${TYPIST_SUPABASE_KEY}
      ITEM_CATALOGUE_SUPABASE_KEY: ${ITEM_CATALOGUE_SUPABASE_KEY}
